export enum queryKey {
  brand = "getBrand",
  category = "getCategory",
  cpu = "getCpu",
  manufacturer = "getManufacturer",
  operationSystem = "getOperationSystem",
  screenResolution = "getScreenResolution",
  staffs = "getStaffs",
  detail_staff = "getDetailStaff",
  staff_common_select = "getStaffCommonSelect",
  roles = "getRole",
  detail_role = "getDetailRole",
  role_search = "getRoleSearch",
  students = "getStudents",
  student_detail = "getStudentDetail",
  student_search_all = "getStudentSearch",
  student_search_department_campus = "getStudentSearchDepartmentCampus",
}
